# Generated by Django 4.1.5 on 2023-02-08 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('RH+', 'RH+')], max_length=3)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('smoker_status', models.CharField(choices=[('C', 'Current'), ('F', 'Former'), ('N', 'Never')], max_length=1)),
                ('heart_rate', models.IntegerField()),
                ('alcoholic', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('balenced_diet', models.CharField(choices=[('R', 'Regularly'), ('S', 'Seldom'), ('N', 'Never')], max_length=1)),
                ('exercise', models.CharField(choices=[('R', 'Regularly'), ('S', 'Seldom'), ('N', 'Never')], max_length=1)),
                ('pre_heart_cond', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('family_heart_cond', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('diabetic', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('blood_pressure', models.IntegerField()),
                ('bp_hypert', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('hypert_treatment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('asprin_treatment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('lipid_level', models.IntegerField()),
                ('statin', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('non_cardiac_ailment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('non_cardiac_treatment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('psychiatric_health_cond', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('sugar_level', models.CharField(blank=True, max_length=3, null=True)),
                ('psychiatric_health_cond_name', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
